server:
  port: 8002

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.alfie.springcloud.entities


spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.37.255.120:3306/cloud2020?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: mysqlroot


eureka:
  client:
    #
    fetch-registry: true
    register-with-eureka: true
    service-url:
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    instance-id: patyment8002
    prefer-ip-address: true